name: Build docker image on tag and publish to ghcr

on:
  push:
    paths:
      - devenv/**.nix
      - devenv/flake.lock

defaults:
  run:
    working-directory: ./devenv

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Build image
        run: "nix build .#container"
      - name: Log into ghcr
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Load and push image
        run: |
          load_message=$(docker load < result)
          image_name=$(echo "$load_message" | awk -F':' '{print $2}' | xargs)
          image_tag=$(echo "$load_message" | awk -F':' '{print $3}' | xargs)

          docker tag "$image_name:$image_tag" "ghcr.io/$image_name:latest"
          docker push "ghcr.io/$image_name:latest"
